### PR TITLE
feat: added bot edge detection

### PR DESCRIPTION
**Pull request by srikaanthtb**
my implementation of the bot edge logic

### CODE REVIEW

**Comment by srikaanthtb** [comment]
i've done a quick check and this does not have the bug where the bot's position will sometime be 0

**Comment by WarrenHawker** [comment]
> i've done a quick check and this does not have the bug where the bot's position will sometime be 0

Yes, I'm not sure why it's happening, but I'm adding extra measure in the getRandomNumber function to stop it from happening. Will push commit in a moment.

**Review by ayequill — APPROVED** [review]
Works. Awesome

**Review by WarrenHawker — APPROVED** [review]
LGTM

**Pull request merged**
