### PR TITLE
Battle grid

### PR DESCRIPTION
**Pull request by srikaanthtb**
small fix that an ID to the grid to make it easy to track position of the bots

### CODE REVIEW

**Review by WarrenHawker — APPROVED** [review]

**Review by ayequill — APPROVED** [review]

**Comment by ayequill** [comment]
- I generated 4 bots randomly to render them
- the useEffect runs twice because of strict mode.
   You can disable it temporary so that it generates the exact amount of
   bots passed. But it doesn't happen in production, so we can turn it on
   when building
- I am displaying the bots by their name. I havent implemented the colors yet. 
- Working on the movement as well.

**Comment by ayequill** [comment]
There is a bug where sometimes not all 4 bots are displayed. Still working on it. Might be the bot renderer prop.

**Comment by srikaanthtb** [comment]
took a look and I think it's because in your use effect function you had an empty dependency in there which is throwing it off.

**Comment by ayequill** [comment]
> dependency

No doing that will cause an infinite loop. An empty deps indicates it runs only once the component mounts.

**Pull request closed without merging**
