### PR TITLE
Feature/welcome page

### PR DESCRIPTION
**Pull request by hannakozak**
Created basic layout component with Header and Footer.
Added welcome page without styling.

### CODE REVIEW

**Review by WarrenHawker — COMMENTED** [review]
Overall looks good. The only thing obvious missing right now is a way to change the displayed component. Could you create a state which allows us to toggle between the "welcome" page, the "bot config" page and the "battle" page please.

**Comment by hannakozak** [comment]
> Overall looks good. The only thing obvious missing right now is a way to change the displayed component. Could you create a state which allows us to toggle between the "welcome" page, the "bot config" page and the "battle" page please.

Yes, no problem with that. We can add routing or place a battle page and configuration under the welcome page.  How do you prefer?

**Comment by WarrenHawker** [comment]
> > Overall looks good. The only thing obvious missing right now is a way to change the displayed component. Could you create a state which allows us to toggle between the "welcome" page, the "bot config" page and the "battle" page please.
> 
> Yes, no problem with that. We can add routing or place a battle page and configuration under the welcome page. How do you prefer?

I don't think there's much benefit in adding React-Router to a project like this, so for now let's just have a piece of state that tells the app which component to display.

**Comment by hannakozak** [comment]
> > > Overall looks good. The only thing obvious missing right now is a way to change the displayed component. Could you create a state which allows us to toggle between the "welcome" page, the "bot config" page and the "battle" page please.
> > 
> > 
> > Yes, no problem with that. We can add routing or place a battle page and configuration under the welcome page. How do you prefer?
> 
> I don't think there's much benefit in adding React-Router to a project like this, so for now let's just have a piece of state that tells the app which component to display.

**Comment by ayequill** [comment]
We can use conditional rendering for that.

**Review by WarrenHawker — APPROVED** [review]

**Review by ayequill — APPROVED** [review]

**Pull request merged**
